name: 'r-hub/actions/setup-r-netbsd'
description: |
  Setup a NetBSD VM with R. Run this action on `ubuntu-latest`.
  Based on https://github.com/vmactions/netbsd-vm.
author: 'Gábor Csárdi'

inputs:
  release:
    description: 'The release version of NetBSD VM.'
    required: false
    default: '10.0'

runs:
  using: "composite"
  steps:

  - name: Start NetBSD VM. This might take 2-3 minutes.
    uses: vmactions/netbsd-vm@v1
    with:
      release: ${{ inputs.release || '10.0' }}
      envs: 'RUNNER_TEMP R_LIBS_USER'
      sync: sshfs
      run: |
        uname -a

  - name: Set up R library for caching
    run: |
      R_LIBS_USER=${RUNNER_TEMP}/Library
      echo "R_LIBS_USER=${R_LIBS_USER}" >> ${GITHUB_ENV}
      mkdir -p "${R_LIBS_USER}"
    shell: bash

  - run: |
      # Install R and pak
      echo "::group::Install R"
      # Missing locales (?) cause crashes otherwise
      unset LANG
      # Install some system packages, so we can install tidyverse, devtools
      pkg_add R gmake libxml2 libgit2
      echo "::endgroup::"
      echo "::group::Configure R"
      ncpu=`(grep -c ^processor /proc/cpuinfo) || echo 4`
      echo "options(Ncpus=${ncpu})" >> ~/.Rprofile
      R -q -e 'dir.create(Sys.getenv("R_LIBS_SITE"), showWarnings = FALSE, recursive = TRUE)'
      echo 'export LC_COLLATE=C' >> /etc/profile
      echo 'unset LANG' >> /etc/profile
      echo 'export MAKE=gmake' >> /etc/profile
      curl -LO https://raw.githubusercontent.com/r-hub/containers/refs/heads/main/dependencies/checkbashisms/checkbashisms
      mkdir -p /usr/local/bin
      mv checkbashisms /usr/local/bin/
      sed -i.bak 's|/usr/bin/perl|/usr/bin/env perl|' /usr/local/bin/checkbashisms
      rm /usr/local/bin/checkbashisms.bak
      chmod +x /usr/local/bin/checkbashisms
      echo "::endgroup::"
      echo "::group::Install pak"
      R -q -e 'install.packages("pak", lib = Sys.getenv("R_LIBS_SITE"), repos = sprintf(
                 "https://r-lib.github.io/p/pak/devel/%s/%s/%s",
                 .Platform$pkgType,
                 R.Version()$os,
                 R.Version()$arch
               ))'
      echo "::endgroup::"
    shell: netbsd {0}

  - name: Set up remote shell
    run: |
      cp ${{ github.action_path }}/Rscript \
        /usr/local/bin/Rscript
      chmod 775 /usr/local/bin/Rscript
    shell: bash

  - name: Test R in NetBSD VM
    run: |
      getRversion()
      R.version[["platform"]]
      .libPaths()
      .Library
      Sys.getenv("R_LIBS_SITE")
      Sys.getenv("R_LIBS_USER")
      find.package("pak")
    shell: Rscript {0}
