name: 'r-hub/actions/setup-r-freebsd'
description: |
  Setup a FreeBSD VM with R. Run this action on `ubuntu-latest`.
  Based on https://github.com/vmactions/freebsd-vm.
author: 'Gábor Csárdi'

inputs:
  release:
    description: 'The release version of FreeBSD VM.'
    required: false

runs:
  using: "composite"
  steps:

  - name: Start FreeBSD VM. This might take 2-3 minutes.
    uses: vmactions/freebsd-vm@v1
    with:
      envs: 'RUNNER_TEMP'
      sync: sshfs
      run: |
        freebsd-version
        ln -s /usr/share/zoneinfo/Europe/Madrid  /etc/localtime

  - name: Set up R library for caching
    run: |
      R_LIBS_USER=${RUNNER_TEMP}/Library
      echo "R_LIBS_USER=${R_LIBS_USER}" >> ${GITHUB_ENV}
      mkdir -p "${R_LIBS_USER}"
    shell: bash

  - name: Install R and pak
    run: |
      pkg install -y R
      ncpu=`(sysctl dev.cpu | grep location | wc -l) || echo 4`
      echo "options(Ncpus=${ncpu})" >> ~/.Rprofile
      R -q -e 'dir.create(Sys.getenv("R_LIBS_SITE"), showWarnings = FALSE, recursive = TRUE)'
      R -q -e 'install.packages("pak", lib = Sys.getenv("R_LIBS_SITE"), repos = "https://cran.rstudio.com")'
    shell: freebsd {0}

  - name: Set up remote shell
    run: |
      cp ${{ github.action_path }}/Rscript \
        /usr/local/bin/Rscript
      chmod 775 /usr/local/bin/Rscript
    shell: bash

  - name: Test R in FreeBSD VM
    run: |
      getRversion()
      R.version[["platform"]]
    shell: Rscript {0}
