name: 'r-hub/actions/debug-shell'
description: |
  Start a debug shell via tmate, if the run is a re-run in debug mode.
  Uses the mxschmitt/action-tmate action internally.
author: 'Gábor Csárdi'

inputs:
  connect-timeout-seconds:
    description: |
      How long in seconds to wait for a connection to be established.
    required: false
    default: '600'

runs:
  using: "composite"
  steps:

  - name: Install MSYS2 on Windows
    if: ${{ always() && runner.debug == '1' && github.run_attempt != '1' && runner.os == 'Windows' }}
    uses: msys2/setup-msys2@v2
    id: setup-msys2

  - name: Start debug shell, if this is a debug re-run.
    uses: mxschmitt/action-tmate@v3.22
    if: ${{ always() && runner.debug == '1' && github.run_attempt != '1' && runner.os != 'Windows' }}
    with:
      limit-access-to-actor: true
      detached: true
      connect-timeout-seconds: ${{ inputs.connect-timeout-seconds || '600' }}

  - uses: mxschmitt/action-tmate@v3.22
    if: ${{ always() && runner.debug == '1' && github.run_attempt != '1' && runner.os == 'Windows' }}
    with:
      msys2-location: ${{ steps.setup-msys2.outputs.msys2-location }}
      limit-access-to-actor: true
      detached: true
      connect-timeout-seconds: ${{ inputs.connect-timeout-seconds || '600' }}
