name: 'r-hub/actions/debug-shell'
description: |
  Start a debug shell via tmate, if the run is a re-run in debug mode.
author: 'Gábor Csárdi'

runs:
  using: "composite"
  steps:

  - name: Start debug shell, if this is a debug re-run.
    uses: mxschmitt/action-tmate@v3
    if: ${{ runner.debug == "1" && github.run_attempt != "1" }}
    with:
      limit-access-to-actor: true
      detached: true
