name: format-r-code-release.yaml
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    name: build
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-latest,    arch: amd64 }
          - { os: ubuntu-24.04-arm, arch: arm64 }
    outputs:
      image-uri: "ghcr.io/r-hub/actions/format-r-code-${{ matrix.config.arch }}:latest"
    steps:
    - uses: actions/checkout@v4
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build
      uses: docker/build-push-action@v5
      with:
        platforms: linux/${{ matrix.config.arch }}
        provenance: false
        context: format-r-code
        push: true
        outputs:
        tags: "ghcr.io/r-hub/actions/format-r-code-${{ matrix.config.arch }}:latest"

  manifest:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - run: |
        docker buildx imagetools create -t ghcr.io/r-hub/actions/format-r-code:latest \
          ghcr.io/r-hub/actions/format-r-code-amd64:latest \
          ghcr.io/r-hub/actions/format-r-code-arm64:latest
      shell: bash
